### ISSUE TITLE
Tab ordering on Workbook

### ISSUE THREAD

**Issue by MiguelAlonso1** [mbleron/ExcelGen#1]
Hi there,

I have an array of 6 to 20 queries with named tabs that I feed to ExcelGen.addSheetFromQuery. However, I noticed that EXCELGEN is somehow reordering the resulting tabs on the workbook in alphabetical order. How can we use the order specified by the array order?

**Comment by mbleron** [comment]
Hi Miguel,

Thanks for reporting this issue.
Internally, I use an associative array indexed by the sheet name to cache each sheet definition.
When generating the workbook, I iterate that array in key order, that's why sheets end up sorted in alphabetical order.

I'll provide a fix in the next few days.

**Comment by MiguelAlonso1** [comment]
This is working perfectly now! Thanks, Marc!
