### ISSUE TITLE
not printable/special character may corrupt excel file

### ISSUE THREAD

**Issue by wickyhu** [mbleron/ExcelGen#12]
Hi,

I found when some not printable/special characters in string, the generated excel file cannot be opened.

This is a case I met:

`
[test.xlsx](https://github.com/mbleron/ExcelGen/files/7162992/test.xlsx)
select '' f1, ascii('') f2, length('') f3, lengthb('') f4 from dual
F1                              	F2	F3	F4
----------------------	--	--	--
                               	26	1 	1
`

The generated excel of above sql attached for your reference.

Regards
Wicky

**Comment by mbleron** [comment]
Hi Wicky,

Thanks for reporting this.
Due to the XML (1.0) nature of the xlsx format under the hood, control characters [0x00-0x1F] except 0x09, 0x0A and 0x0D are forbidden unless they are escaped in the form `_xHHHH_` (ref. [ECMA-376](https://www.ecma-international.org/wp-content/uploads/ECMA-376-Fifth-Edition-Part-1-Fundamentals-And-Markup-Language-Reference.zip)).
I have to admit I overlooked that part of the specs.

That being said, would you like to :

1. keep those characters in the resulting file, with some performance overhead due to the escape process (*) ?
2. remove those characters while generating the file?

(*) could be mitigated if disabled by default, or enabled on a per-column basis

**Comment by wickyhu** [comment]
Hi,

Thank you for the prompt response.
I don't want the invisible character in file,
I think option 2 should be better for most of cases.

Regards
Wicky

**Comment by mbleron** [comment]
Fixed in v2.2.1
By default, control characters are now removed from string values.
I'll add later a few options to control this more finely.
