### ISSUE TITLE
ExcelGen.addSheetFromQuery

### ISSUE THREAD

**Issue by pwinning** [mbleron/ExcelGen#14]
hi, could anyone help i am trying to figure a way to multiple table datasets outputted to one sheet and defined in ExcelGen.addSheetFromQuery which column the data will go into any help would be much appreciated

**Comment by mbleron** [comment]
Hi,
If I understand correctly, you want to output the results of different source queries into the same sheet, in the form of different sub-tables?
That's not currently possible, the API only allows a unique source query per sheet.

I'll mark this as an enhancement request.

Thanks.

**Comment by lee-lindley** [comment]
I've encountered a surprising number of these sub-tables in reconciliation spreadsheets with my current client. For the common case of wanting them stacked vertically, I hope you will consider a parameter to control the gap or space between the two result sets.

In addition I have a requirement for side by side, semi-related queries that I can satisfy with a full outer join on a row-number column from each query (after ordering them independently). It works, but is weird. If your sub-table design supports horizontal placement (relative or absolute) as well as vertical relative placement, it will be very powerful. Since there is a way to do it with SQL, perhaps the need to support horizontal sub-table placement is not that compelling.

**Comment by mbleron** [comment]
Yes, tables may be positioned relatively to each other, in a hierarchical fashion, using offsets from a reference point in the parent table. 
It will be available for individual cell placement as well.

**Comment by mbleron** [comment]
Implemented in v3.0.
See [addTable](https://github.com/mbleron/ExcelGen#addtable-function) procedure, and for example: 
* [Relative positioning](https://github.com/mbleron/ExcelGen#relative-positioning)
* [Master-details](https://github.com/mbleron/ExcelGen#master-details)

**Comment by pwinning** [comment]
Hi, I am relatively new to the oracle sql world and wondered is it possible to have the excelGen output a chart within a sheet?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
