### ISSUE TITLE
setDefaultStyle no setting font

### ISSUE THREAD

**Issue by lee-lindley** [mbleron/ExcelGen#43]
Apologies for not testing this earlier. I know it was my use case and request that led to this functionality.

Attached test case is configured to set the default style for the entire workbook. Commented out below creation of the sheet is setting it for a single sheet. Neither cause the cell content to use the specified font, while using that same cell style handle with setTableColumnProperties works just fine.
If I'm doing something wrong, it is not obvious. Please advise.
[default_style_bug.zip](https://github.com/mbleron/ExcelGen/files/10569591/default_style_bug.zip)

**Comment by mbleron** [comment]
I knew this one was gonna come back to bite me :)
The inheritance is broken between sheet level and table column level because there's no sheet column settings.
I have to admit the [documentation](https://github.com/mbleron/ExcelGen#style-inheritance) is not that clear in this regard.

I'll fix it for tomorrow.

**Comment by lee-lindley** [comment]
confirmed setDefaultStyle at sheet level is working as designed. Thanks Marc.
