### ISSUE TITLE
Set the name and width of the column

### ISSUE THREAD

**Issue by melDavila** [mbleron/ExcelGen#7]
Currently 'Column names are derived from SQL source query'.

Would it be possible to set the column name?
This will avoid Oracle limits.

Currently, the width of the column is the same for everyone.
Would it be possible to set the width of the column, as part of format?

procedure setColumnFormat (
  p_ctxId     in ctxHandle
, p_sheetId   in sheetHandle 
, p_columnId  in pls_integer
, p_format    in varchar2
, p_column_name    in varchar2 [ NO MANDATORY ]
, p_column_width    in NUMBER [ NO MANDATORY ]
);

For example for this QUERY:
SELECT 1 as "This is the name of this column to test the name ÑÄÖÜ" from dual;

ExcelGen.addSheetFromQuery(ctxId, 'test', 'SELECT 1 as "This is the name of this column to test the name ÑÄÖÜß" from dual ');

Has this error:
ERROR SQLERRM: ORA-06502: PL / SQL: numeric or value error: string buffer too small

ORA-06512: in "SYS.DBMS_SQL", line  2084
ORA-06512: in "ARCHIVDBAP.EXCELGEN", line  1131
ORA-06512: in "ARCHIVDBAP.EXCELGEN", line  1199
ORA-06512: in "ARCHIVDBAP.EXCELGEN", line 2176
ORA-06512: in "ARCHIVDBAP.EXCELGEN", line 3007
ORA-06512: in "ARCHIVDBAP.TEST", line  90

**Comment by mbleron** [comment]
I guess you're on Oracle 12.2+ as identifiers can now be up to 128 bytes, otherwise you would have hit `ORA-00972: identifier is too long`.
The error "string buffer too small" is a bug in my code actually, or more precisely a lack of support for long identifiers. It's an easy fix.
Anyway, I'm adding your request to the list of upcoming new features as well.

**Comment by mbleron** [comment]
Done in v2.4.
See [setColumnFormat](https://github.com/mbleron/ExcelGen#setcolumnformat-procedure) procedure.
